### ISSUE TITLE
Reoccurring error log in home assistant - KeyError  'latest_sensor_values'

### ISSUE THREAD

**Issue by brandstaetter** [fredrike/pypoint#12]
```
2023-08-24 03:39:44.537 ERROR (MainThread) [homeassistant.util.logging] Exception in _update_callback when dispatching 'point_update': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/point/sensor.py", line 101, in _update_callback
    self._value = await self.device.sensor(self.device_class)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypoint/__init__.py", line 313, in sensor
    return await self._session.read_sensor(self.device_id, sensor_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypoint/__init__.py", line 173, in read_sensor
    self._device_state[device_id]["latest_sensor_values"][sensor_uri]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'latest_sensor_values'
```

**Comment by fredrike** [comment]
Fixed in #13
